"$schema" = 'https://starship.rs/config-schema.json'

command_timeout = 1500
palette = "rose-pine-moon"

format = """
$hostname\
$directory\
[î‚¶](fg:overlay)$git_branch$git_status[î‚´](fg:overlay)\
$line_break$character"""

[battery]
disabled = true
[cmd_duration]
disabled = true

[palettes.rose-pine-moon]
overlay = '#393552'
love = '#eb6f92'
gold = '#f6c177'
rose = '#ea9a97'
pine = '#3e8fb0'
foam = '#9ccfd8'
iris = '#c4a7e7'
subtle = '#908caa'

[hostname]
ssh_only = false
style = "bg:overlay fg:subtle"
disabled = false
ssh_symbol = 'ğŸŒ'
format = "[î‚¶](fg:overlay)[ ï„‰  $hostname $ssh_symbol ]($style)[î‚´](fg:overlay) "

[character]
success_symbol = "[â¯](gold)"
error_symbol = "[â¯](gold)"
vimcmd_symbol = "[â®](overlay)"

[directory]
format = "[î‚¶](fg:overlay)[ $path ]($style)[î‚´](fg:overlay) "
style = "bg:overlay fg:foam"
truncation_length = 2
truncation_symbol = "â€¦/"

[git_branch]
format = "[ $symbol $branch ]($style)"
style = "bg:overlay fg:foam"
symbol = "ï˜"

[git_status]
disabled = false
style = "bg:overlay fg:subtle"
format = '([$all_status$ahead_behind]($style))'
