"$schema" = 'https://starship.rs/config-schema.json'

command_timeout = 1500
palette = "rose-pine-moon"

#format = """
#$hostname\
#$directory\
#$git_branch\
#$git_status\
#$docker_context\
#$package\
#$bun\
#$deno\
#$dotnet\
#$elixir\
#$erlang\
#$gleam\
#$golang\
#$lua\
#$nodejs\
#$pulumi\
#$python\
#$ruby\
#$swift\
#$terraform\
#$zig\
#$nix_shell\
#$conda\
#$line_break$character"""

format = """
$hostname\
$directory\
$git_branch\
$git_status\
$line_break$character"""

[battery]
disabled = true
[cmd_duration]
disabled = true

[palettes.rose-pine-moon]
overlay = '#393552'
love = '#eb6f92'
gold = '#f6c177'
rose = '#ea9a97'
pine = '#3e8fb0'
foam = '#9ccfd8'
iris = '#c4a7e7'
subtle = '#908caa'

[username]
format = "[ÓÇ∂](fg:overlay)[ ÔÄá $user ]($style)[ÓÇ¥](fg:overlay) "
show_always = true
style_root = "bg:overlay fg:iris"
style_user = "bg:overlay fg:subtle"

[hostname]
ssh_only = false
style = "bg:overlay fg:subtle"
disabled = false
ssh_symbol = 'üåê'
format = "[ÓÇ∂](fg:overlay)[ ÔÑâ  $hostname $ssh_symbol ]($style)[ÓÇ¥](fg:overlay) "

[character]
success_symbol = "[‚ùØ](gold)"
error_symbol = "[‚ùØ](gold)"
vimcmd_symbol = "[‚ùÆ](overlay)"


[directory]
format = "[ÓÇ∂](fg:overlay)[ $path ]($style)[ÓÇ¥](fg:overlay) "
style = "bg:overlay fg:foam"
truncation_length = 2
truncation_symbol = "‚Ä¶/"

[git_branch]
format = "[ÓÇ∂](fg:overlay)[ $symbol $branch ]($style)[ÓÇ¥](fg:overlay) "
style = "bg:overlay fg:foam"
symbol = "Ôêò"

[git_status]
disabled = false
style = "fg:love"
format = '([$all_status]($style))'
untracked = '[?\($count\)](fg:gold)'
stashed = '[\$](fg:iris)'
modified = '[!\($count\)](fg:gold)'
renamed = '[¬ª\($count\)](fg:iris)'
deleted = '[‚úò\($count\)](style)'
staged = '[++\($count\)](fg:gold)'
